CREATE TABLE MONITORINGDBA.INITORA_PARAMETERS_TABLE
(
  PK_SG_NUMBER  NUMBER                          NOT NULL,
  PARAMETERS    VARCHAR2(50),
  ORACLE11G     VARCHAR2(50),
  ORACLE12C     VARCHAR2(50)
);


ALTER TABLE MONITORINGDBA.INITORA_PARAMETERS_TABLE ADD (
  CONSTRAINT INITORA_PARAMETERS_TABLE_PK
  PRIMARY KEY
  (PK_SG_NUMBER)
  ENABLE VALIDATE);